bind 0.0.0.0
port 6379
protected-mode no

maxmemory 256mb
maxmemory-policy noeviction

appendonly yes
appendfsync everysec
save ""

stream-node-max-bytes 4096
stream-node-max-entries 100

tcp-keepalive 60
timeout 0

